[workspace]
members = []

[package]
name = "project-resonate"
version = "0.1.0"
description = "A native, open-source music platform"
authors = ["you"]
edition = "2021"
default-run = "project-resonate"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
tauri-plugin-dialog = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lofty = "0.24.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
walkdir = "2.5.0"
uuid = { version = "1.24.0", features = ["v4"] }
rodio = { version = "0.19", default-features = false, features = ["symphonia-all"] }
tokio = { version = "1.0", features = ["time"] }


[profile.release]
opt-level = "z"
